[program:blueprint-hr-critical]
process_name=%(program_name)s_%(process_num)02d
directory=/var/www/blueprint-hr
command=/usr/bin/php artisan queue:work redis --queue=critical,default --sleep=3 --tries=5 --timeout=120 --backoff=60 --max-time=3600 --memory=512
autostart=true
autorestart=true
startsecs=5
stopasgroup=true
killasgroup=true
stopwaitsecs=3600
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/blueprint-hr-critical.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=10

[program:blueprint-hr-emails]
process_name=%(program_name)s_%(process_num)02d
directory=/var/www/blueprint-hr
command=/usr/bin/php artisan queue:work redis --queue=emails --sleep=3 --tries=5 --timeout=120 --backoff=60 --max-time=3600 --memory=512
autostart=true
autorestart=true
startsecs=5
stopasgroup=true
killasgroup=true
stopwaitsecs=3600
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/log/blueprint-hr-emails.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=10

[program:blueprint-hr-reports]
process_name=%(program_name)s_%(process_num)02d
directory=/var/www/blueprint-hr
command=/usr/bin/php artisan queue:work redis --queue=reports --sleep=3 --tries=3 --timeout=300 --backoff=120 --max-time=3600 --memory=768
autostart=true
autorestart=true
startsecs=5
stopasgroup=true
killasgroup=true
stopwaitsecs=3600
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/blueprint-hr-reports.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=10
