<script setup>
import { computed, onMounted, reactive, ref } from 'vue';
import axios from 'axios';

const user = ref(null);
const loading = ref(false);
const error = ref('');
const active = ref('dashboard');
const dashboard = ref({ metrics: {}, employees: [], periods: [], recent_audit: [], tenant: null });
const employees = ref({ data: [] });
const organization = ref({ branches: [], departments: [], designations: [], grades: [], employment_types: [] });
const leave = ref({ types: [], balances: [], requests: [] });
const payroll = ref({ periods: [], transactions: [] });
const login = reactive({ email: '', password: '', remember: false });
const employeeForm = reactive({ employee_no:'', first_name:'', middle_name:'', last_name:'', email:'', phone:'', employment_status:'Active', basic_salary:0, branch_id:null, department_id:null });
const leaveForm = reactive({ employee_id:null, leave_type_id:null, start_date:'', end_date:'', days_requested:1, reason:'' });

const role = computed(() => user.value?.role?.value || user.value?.role || 'Employee');
const isEmployee = computed(() => role.value === 'Employee');
const canManagePeople = computed(() => ['Super Admin','Company Admin','HR Manager'].includes(role.value));
const canProcessPayroll = computed(() => ['Super Admin','Company Admin','Payroll Manager'].includes(role.value));
const money = (value) => new Intl.NumberFormat('en-KE', { style:'currency', currency:'KES', maximumFractionDigits:0 }).format(Number(value || 0));
const fullName = (row) => row?.full_name || [row?.first_name,row?.middle_name,row?.last_name].filter(Boolean).join(' ');

async function apiGet(url, params = {}) { const response = await axios.get(url, { params }); return response.data; }
async function loadAll() { loading.value = true; error.value = ''; try { dashboard.value = await apiGet('/api/dashboard'); employees.value = await apiGet('/api/employees'); organization.value = await apiGet('/api/organization'); leave.value = await apiGet('/api/leave'); payroll.value = await apiGet('/api/payroll'); } catch (e) { error.value = e.response?.data?.message || 'Unable to load HR data.'; } finally { loading.value = false; } }
async function signIn() { loading.value = true; error.value = ''; try { await axios.get('/sanctum/csrf-cookie'); const response = await axios.post('/api/auth/login', login); user.value = response.data.user; await loadAll(); } catch (e) { error.value = e.response?.data?.message || 'Sign in failed.'; } finally { loading.value = false; } }
async function signOut() { await axios.post('/api/auth/logout'); user.value = null; }
async function createEmployee() { error.value=''; try { await axios.post('/api/employees', employeeForm); Object.assign(employeeForm,{employee_no:'',first_name:'',middle_name:'',last_name:'',email:'',phone:'',employment_status:'Active',basic_salary:0,branch_id:null,department_id:null}); await loadAll(); active.value='employees'; } catch(e) { error.value=e.response?.data?.message || 'Could not create employee.'; } }
async function submitLeave() { try { await axios.post('/api/leave/requests', leaveForm); Object.assign(leaveForm,{employee_id:null,leave_type_id:null,start_date:'',end_date:'',days_requested:1,reason:''}); await loadAll(); } catch(e) { error.value=e.response?.data?.message || 'Could not submit leave request.'; } }
async function decideLeave(request, status) { try { await axios.post(`/api/leave/requests/${request.id}/decision`, { status, decision_comment: status === 'Approved' ? 'Approved in HR workspace' : 'Decision recorded in HR workspace' }); await loadAll(); } catch(e) { error.value=e.response?.data?.message || 'Could not update leave request.'; } }
async function processPayroll(periodId) { if (!periodId) return; try { await axios.post('/api/payroll/process', { payroll_period_id: periodId }); await loadAll(); active.value='payroll'; } catch(e) { error.value=e.response?.data?.message || 'Could not process payroll.'; } }
function downloadEmployees() { window.location.href = '/api/reports/employees.xlsx'; }
function downloadPayslip(transactionId) { window.location.href = `/api/reports/payslips/${transactionId}.pdf`; }
onMounted(async () => { try { const response=await apiGet('/api/auth/me'); user.value=response.user; await loadAll(); } catch (_) {} });
</script>

<template>
  <div v-if="!user" class="min-vh-100 d-flex align-items-center justify-content-center bg-dark-subtle p-3">
    <div class="card login-card border-0 p-4 p-md-5">
      <div class="d-flex align-items-center gap-3 mb-4"><div class="brand-mark">BP</div><div><div class="fw-bold fs-4">BluePrint HR</div><div class="text-secondary small">People, payroll and compliance</div></div></div>
      <h1 class="h4 fw-bold">Sign in</h1><p class="text-secondary">Use your organization account to continue.</p>
      <div v-if="error" class="alert alert-danger py-2">{{ error }}</div>
      <form @submit.prevent="signIn">
        <div class="mb-3"><label class="form-label">Email</label><input v-model="login.email" type="email" class="form-control" required autocomplete="email"></div>
        <div class="mb-3"><label class="form-label">Password</label><input v-model="login.password" type="password" class="form-control" required autocomplete="current-password"></div>
        <div class="form-check mb-3"><input v-model="login.remember" class="form-check-input" type="checkbox" id="remember"><label class="form-check-label" for="remember">Remember me</label></div>
        <button class="btn btn-primary w-100" :disabled="loading">{{ loading ? 'Signing in…' : 'Sign in securely' }}</button>
      </form>
      <div class="small text-secondary mt-4">Development seed credentials are documented in the Laravel README. Rotate them before production.</div>
    </div>
  </div>

  <div v-else class="app-shell d-flex">
    <aside class="sidebar d-flex flex-column py-3">
      <div class="px-3 d-flex align-items-center gap-2 mb-4"><div class="brand-mark">BP</div><div class="brand-copy"><div class="fw-bold">BluePrint HR</div><div class="small text-white-50">HR Operations</div></div></div>
      <nav class="nav flex-column">
        <a v-for="item in [{key:'dashboard',label:'Dashboard',icon:'bi-speedometer2'},{key:'employees',label:'Employees',icon:'bi-people'},{key:'organization',label:'Organization',icon:'bi-diagram-3'},{key:'leave',label:'Leave',icon:'bi-calendar2-check'},{key:'payroll',label:'Payroll',icon:'bi-calculator'},{key:'ess',label:'My ESS',icon:'bi-person-badge'},{key:'audit',label:'Audit Trail',icon:'bi-shield-check'}]" :key="item.key" href="#" class="nav-link d-flex align-items-center gap-3 py-2" :class="{active:active===item.key}" @click.prevent="active=item.key"><i class="bi" :class="item.icon"></i><span class="nav-label">{{ item.label }}</span></a>
      </nav>
      <div class="mt-auto px-3 user-copy"><div class="small text-white-50">Signed in as</div><div class="fw-semibold text-truncate">{{ user.name }}</div><div class="small text-white-50">{{ role }}</div><button class="btn btn-sm btn-outline-light mt-3 w-100" @click="signOut">Sign out</button></div>
    </aside>
    <main class="content-area">
      <header class="bg-white border-bottom px-3 px-lg-5 py-3 d-flex justify-content-between align-items-center"><div><div class="text-secondary small">{{ dashboard.tenant?.company_name || 'Organization' }}</div><h1 class="h4 mb-0 fw-bold text-capitalize">{{ active === 'ess' ? 'Employee self-service' : active }}</h1></div><div class="d-flex align-items-center gap-2"><span class="badge text-bg-success">{{ role }}</span><button class="btn btn-light d-lg-none" @click="signOut"><i class="bi bi-box-arrow-right"></i></button></div></header>
      <div class="p-3 p-lg-5">
        <div v-if="error" class="alert alert-danger">{{ error }}</div>
        <div v-if="loading" class="alert alert-info d-flex align-items-center gap-2"><span class="spinner-border spinner-border-sm"></span> Loading HR workspace…</div>

        <section v-if="active==='dashboard'" class="space-y-4">
          <div class="row g-3 mb-4"><div v-for="metric in [{label:'Active headcount',value:dashboard.metrics.headcount,icon:'bi-people-fill',tone:'bg-primary-subtle text-primary'},{label:'Payroll gross',value:money(dashboard.metrics.monthly_payroll),icon:'bi-cash-stack',tone:'bg-success-subtle text-success'},{label:'Branches',value:dashboard.metrics.branches,icon:'bi-building',tone:'bg-warning-subtle text-warning-emphasis'},{label:'Pending leave',value:dashboard.metrics.pending_leave,icon:'bi-calendar-event',tone:'bg-info-subtle text-info-emphasis'}]" :key="metric.label" class="col-12 col-sm-6 col-xl-3"><div class="card metric-card h-100"><div class="card-body d-flex justify-content-between"><div><div class="text-secondary small mb-2">{{ metric.label }}</div><div class="fs-3 fw-bold">{{ metric.value }}</div></div><div class="metric-icon" :class="metric.tone"><i class="bi" :class="metric.icon"></i></div></div></div></div></div>
          <div class="row g-4"><div class="col-xl-8"><div class="card border-0 shadow-sm"><div class="card-header bg-white d-flex justify-content-between align-items-center"><div><h2 class="h5 mb-1">Recent employee records</h2><div class="text-secondary small">Tenant-scoped active workforce</div></div><button v-if="canManagePeople" class="btn btn-sm btn-primary" @click="active='employees'">Manage employees</button></div><div class="table-responsive"><table class="table table-hover mb-0"><thead><tr><th>Employee</th><th>Department</th><th>Status</th><th class="text-end">Basic salary</th></tr></thead><tbody><tr v-for="employee in dashboard.employees" :key="employee.id"><td><div class="fw-semibold">{{ fullName(employee) }}</div><div class="text-secondary small">{{ employee.employee_no }}</div></td><td>{{ employee.department?.name || '—' }}</td><td><span class="badge text-bg-success">{{ employee.employment_status }}</span></td><td class="text-end">{{ money(employee.basic_salary) }}</td></tr><tr v-if="!dashboard.employees.length"><td colspan="4" class="text-center text-secondary py-4">No employee records yet.</td></tr></tbody></table></div></div></div><div class="col-xl-4"><div class="card border-0 shadow-sm h-100"><div class="card-body"><h2 class="h5">Tenant overview</h2><dl class="row small mt-3 mb-0"><dt class="col-5 text-secondary">KRA PIN</dt><dd class="col-7">{{ dashboard.tenant?.kra_pin || '—' }}</dd><dt class="col-5 text-secondary">Email</dt><dd class="col-7 text-break">{{ dashboard.tenant?.email || '—' }}</dd><dt class="col-5 text-secondary">Phone</dt><dd class="col-7">{{ dashboard.tenant?.phone || '—' }}</dd><dt class="col-5 text-secondary">Address</dt><dd class="col-7">{{ dashboard.tenant?.address || '—' }}</dd></dl></div></div></div></div>
        </section>

        <section v-else-if="active==='employees'"><div class="d-flex justify-content-between align-items-start mb-4"><div><h2 class="h4">Employee master</h2><p class="text-secondary">Manage profiles, statutory identifiers, salary and bank details.</p></div><button v-if="canManagePeople" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#employeeModal"><i class="bi bi-plus-lg"></i> Add employee</button></div><div class="card border-0 shadow-sm"><div class="card-header bg-white d-flex justify-content-between"><span class="fw-semibold">{{ employees.total || employees.data?.length || 0 }} records</span><button v-if="canManagePeople" class="btn btn-sm btn-outline-success" @click="downloadEmployees"><i class="bi bi-file-earmark-excel"></i> Export Excel</button></div><div class="table-responsive"><table class="table table-hover mb-0"><thead><tr><th>Employee</th><th>Contact</th><th>Department</th><th>Status</th><th class="text-end">Salary</th></tr></thead><tbody><tr v-for="employee in employees.data" :key="employee.id"><td><div class="fw-semibold">{{ fullName(employee) }}</div><div class="text-secondary small">{{ employee.employee_no }}</div></td><td>{{ employee.email || employee.phone || '—' }}</td><td>{{ employee.department?.name || '—' }}</td><td><span class="badge" :class="employee.employment_status==='Active'?'text-bg-success':'text-bg-secondary'">{{ employee.employment_status }}</span></td><td class="text-end">{{ money(employee.basic_salary) }}</td></tr></tbody></table></div></div></section>

        <section v-else-if="active==='organization'"><div class="mb-4"><h2 class="h4">Organization structure</h2><p class="text-secondary">Branches and departments that drive workforce reporting.</p></div><div class="row g-4"><div class="col-lg-6"><div class="card border-0 shadow-sm"><div class="card-header bg-white fw-semibold">Branches</div><ul class="list-group list-group-flush"><li v-for="branch in organization.branches" :key="branch.id" class="list-group-item d-flex justify-content-between"><span>{{ branch.name }}</span><span class="text-secondary">{{ branch.code }}</span></li><li v-if="!organization.branches.length" class="list-group-item text-secondary">No branches configured.</li></ul></div></div><div class="col-lg-6"><div class="card border-0 shadow-sm"><div class="card-header bg-white fw-semibold">Departments</div><ul class="list-group list-group-flush"><li v-for="department in organization.departments" :key="department.id" class="list-group-item d-flex justify-content-between"><span>{{ department.name }}</span><span class="text-secondary">{{ department.code }}</span></li><li v-if="!organization.departments.length" class="list-group-item text-secondary">No departments configured.</li></ul></div></div></div></section>

        <section v-else-if="active==='leave'"><div class="d-flex justify-content-between align-items-start mb-4"><div><h2 class="h4">Leave management</h2><p class="text-secondary">Requests, approvals and tenant-scoped leave balances.</p></div><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#leaveModal"><i class="bi bi-calendar-plus"></i> Request leave</button></div><div class="card border-0 shadow-sm"><div class="table-responsive"><table class="table table-hover mb-0"><thead><tr><th>Employee</th><th>Type</th><th>Dates</th><th>Days</th><th>Status</th><th class="text-end">Actions</th></tr></thead><tbody><tr v-for="request in leave.requests" :key="request.id"><td>{{ fullName(request.employee) }}</td><td>{{ request.leave_type?.name }}</td><td>{{ request.start_date }} – {{ request.end_date }}</td><td>{{ request.days_requested }}</td><td><span class="badge" :class="request.status==='Approved'?'text-bg-success':request.status==='Rejected'?'text-bg-danger':'text-bg-warning'">{{ request.status }}</span></td><td class="text-end"><template v-if="request.status==='Pending' && canManagePeople"><button class="btn btn-sm btn-outline-success me-1" @click="decideLeave(request,'Approved')">Approve</button><button class="btn btn-sm btn-outline-danger" @click="decideLeave(request,'Rejected')">Reject</button></template></td></tr><tr v-if="!leave.requests.length"><td colspan="6" class="text-center text-secondary py-4">No leave requests.</td></tr></tbody></table></div></div></section>

        <section v-else-if="active==='payroll'"><div class="d-flex justify-content-between align-items-start mb-4"><div><h2 class="h4">Kenyan payroll</h2><p class="text-secondary">Configuration-driven PAYE, NSSF, SHIF and housing levy calculations.</p></div><select v-if="canProcessPayroll" class="form-select w-auto" @change="processPayroll($event.target.value)"><option value="">Process a period…</option><option v-for="period in payroll.periods" :key="period.id" :value="period.id">{{ period.name }} ({{ period.status }})</option></select></div><div class="card border-0 shadow-sm"><div class="table-responsive"><table class="table table-hover mb-0"><thead><tr><th>Employee</th><th>Period</th><th>Gross</th><th>PAYE</th><th>NSSF</th><th>SHIF</th><th>Net pay</th><th></th></tr></thead><tbody><tr v-for="transaction in payroll.transactions" :key="transaction.id"><td>{{ fullName(transaction.employee) }}</td><td>{{ transaction.period?.name }}</td><td>{{ money(transaction.gross_pay) }}</td><td>{{ money(transaction.paye) }}</td><td>{{ money(transaction.nssf) }}</td><td>{{ money(transaction.shif) }}</td><td class="fw-semibold">{{ money(transaction.net_pay) }}</td><td><button class="btn btn-sm btn-outline-primary" @click="downloadPayslip(transaction.id)"><i class="bi bi-file-earmark-pdf"></i></button></td></tr><tr v-if="!payroll.transactions.length"><td colspan="8" class="text-center text-secondary py-4">No payroll transactions. Process an open period to calculate payroll.</td></tr></tbody></table></div></div></section>

        <section v-else-if="active==='ess'"><div class="row g-4"><div class="col-lg-5"><div class="card border-0 shadow-sm"><div class="card-body"><h2 class="h5">My profile</h2><div class="fs-4 fw-bold mt-3">{{ fullName(user.employee) || user.name }}</div><div class="text-secondary">{{ user.employee?.employee_no || user.email }}</div><hr><dl class="row small"><dt class="col-5 text-secondary">Department</dt><dd class="col-7">{{ user.employee?.department?.name || '—' }}</dd><dt class="col-5 text-secondary">Email</dt><dd class="col-7">{{ user.email }}</dd><dt class="col-5 text-secondary">Phone</dt><dd class="col-7">{{ user.employee?.phone || user.phone || '—' }}</dd></dl></div></div></div><div class="col-lg-7"><div class="card border-0 shadow-sm"><div class="card-body"><h2 class="h5">Leave balances</h2><div v-for="balance in leave.balances" :key="balance.id" class="d-flex justify-content-between border-bottom py-2"><span>{{ balance.leave_type?.name }}</span><span class="fw-semibold">{{ Number(balance.available_days).toFixed(2) }} days available</span></div><div v-if="!leave.balances.length" class="text-secondary">No balances found.</div></div></div></div></div></section>

        <section v-else-if="active==='audit'"><div class="mb-4"><h2 class="h4">Audit trail</h2><p class="text-secondary">Immutable-style activity history for tenant operations.</p></div><div class="card border-0 shadow-sm"><div class="table-responsive"><table class="table table-hover mb-0"><thead><tr><th>When</th><th>User</th><th>Action</th><th>Entity</th><th>Details</th></tr></thead><tbody><tr v-for="log in dashboard.recent_audit" :key="log.id"><td>{{ log.created_at }}</td><td>{{ log.user?.name || 'System' }}</td><td><span class="badge text-bg-secondary">{{ log.action }}</span></td><td>{{ log.entity_type }} #{{ log.entity_id }}</td><td>{{ log.details || 'Record changed' }}</td></tr></tbody></table></div></div></section>
      </div>
    </main>
  </div>

  <div class="modal fade" id="employeeModal" tabindex="-1"><div class="modal-dialog modal-lg"><div class="modal-content"><form @submit.prevent="createEmployee"><div class="modal-header"><h5 class="modal-title">Register employee</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3"><div class="col-md-4"><label class="form-label">Employee No.</label><input v-model="employeeForm.employee_no" class="form-control" required></div><div class="col-md-4"><label class="form-label">First name</label><input v-model="employeeForm.first_name" class="form-control" required></div><div class="col-md-4"><label class="form-label">Last name</label><input v-model="employeeForm.last_name" class="form-control" required></div><div class="col-md-6"><label class="form-label">Email</label><input v-model="employeeForm.email" type="email" class="form-control"></div><div class="col-md-6"><label class="form-label">Phone</label><input v-model="employeeForm.phone" class="form-control"></div><div class="col-md-6"><label class="form-label">Basic salary (KES)</label><input v-model="employeeForm.basic_salary" type="number" min="0" step="0.01" class="form-control" required></div><div class="col-md-6"><label class="form-label">Status</label><select v-model="employeeForm.employment_status" class="form-select"><option>Active</option><option>Inactive</option><option>On Leave</option></select></div><div class="col-md-6"><label class="form-label">Branch</label><select v-model="employeeForm.branch_id" class="form-select"><option :value="null">Select branch</option><option v-for="branch in organization.branches" :value="branch.id" :key="branch.id">{{ branch.name }}</option></select></div><div class="col-md-6"><label class="form-label">Department</label><select v-model="employeeForm.department_id" class="form-select"><option :value="null">Select department</option><option v-for="department in organization.departments" :value="department.id" :key="department.id">{{ department.name }}</option></select></div></div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Cancel</button><button type="submit" class="btn btn-primary">Save employee</button></div></form></div></div></div>
  <div class="modal fade" id="leaveModal" tabindex="-1"><div class="modal-dialog"><div class="modal-content"><form @submit.prevent="submitLeave"><div class="modal-header"><h5 class="modal-title">Request leave</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div v-if="!isEmployee" class="mb-3"><label class="form-label">Employee ID</label><input v-model="leaveForm.employee_id" type="number" class="form-control"></div><div class="mb-3"><label class="form-label">Leave type</label><select v-model="leaveForm.leave_type_id" class="form-select" required><option :value="null">Select type</option><option v-for="type in leave.types" :key="type.id" :value="type.id">{{ type.name }}</option></select></div><div class="row g-3"><div class="col-6"><label class="form-label">Start date</label><input v-model="leaveForm.start_date" type="date" class="form-control" required></div><div class="col-6"><label class="form-label">End date</label><input v-model="leaveForm.end_date" type="date" class="form-control" required></div></div><div class="mt-3"><label class="form-label">Days requested</label><input v-model="leaveForm.days_requested" type="number" min="0.5" step="0.5" class="form-control" required></div><div class="mt-3"><label class="form-label">Reason</label><textarea v-model="leaveForm.reason" class="form-control" rows="3"></textarea></div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Cancel</button><button type="submit" class="btn btn-primary">Submit request</button></div></form></div></div></div>
</template>
